name: clarified_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.6
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_analytics: ^10.7.0
  firebase_messaging: ^14.7.4
  firebase_storage: ^11.5.1
  firebase_remote_config: ^4.3.4
  flutter_svg: ^2.0.9
  awesome_bottom_bar: ^1.2.4
  flutter_blurhash: ^0.8.2
  flutter_markdown: ^0.6.18+2
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.1
  eventify: ^1.0.1
  image_picker: ^1.0.4
  firebase_app_check:
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.8.1
  autoscale_tabbarview: ^1.0.2
  flutter_localization:
  intl:
  firebase_dynamic_links: ^5.4.8
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.1
  flutter_file_downloader: ^1.2.0
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/subjects/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
