// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRriFlu4m8bzhZwR6TNoNi9it9-5hTco',
    appId: '1:270192308039:android:0fac5204c4aa31e6976662',
    messagingSenderId: '270192308039',
    projectId: 'clarified-1501',
    storageBucket: 'clarified-1501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIGzwkg8y1fDnp7teFtICpTnHepc6Qvs',
    appId: '1:270192308039:ios:8299dd80c1bc2aa1976662',
    messagingSenderId: '270192308039',
    projectId: 'clarified-1501',
    storageBucket: 'clarified-1501.appspot.com',
    androidClientId: '270192308039-gp1kusca6jql89c8bv4hn0ied7cjjrrj.apps.googleusercontent.com',
    iosClientId: '270192308039-sh58kbn606hqonbaml89a56dddoimk7m.apps.googleusercontent.com',
    iosBundleId: 'com.scratchpadlabs.clarified.clarifiedMobile',
  );
}
